/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/brainwing.glb 
*/

import React from "react"
import { useGLTF } from "@react-three/drei"

// Use local file in dev, blob URL in production
const MODEL_URL =
  process.env.NODE_ENV === "development"
    ? "/models/brainwing.glb"
    : "https://hwwniyoikhttldks.public.blob.vercel-storage.com/brainwing.glb"

export function Model(props) {
  const { nodes, materials } = useGLTF(MODEL_URL)

  return (
    <group {...props} dispose={null}>
      <group position={[2938.695, 20, -1246.65]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Roads.geometry} material={materials.adskMatRoads} position={[0, 0, -19.92]} />
      </group>
      <group position={[-125.701, 0, 830.516]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Line001.geometry} material={materials.Material} position={[0, 0, 0.1]} />
      </group>
      <mesh geometry={nodes.Circle.geometry} material={materials.Material} position={[3116.223, 0.493, 1899.346]} scale={76.769} />
      <mesh geometry={nodes.Circle001.geometry} material={materials.Material} position={[3214.262, 0.493, 1153.788]} scale={69.765} />
      <group position={[2076.834, 0, 4293.844]} rotation={[-1.577, 0.004, -1.958]} scale={0.832}>
        <mesh geometry={nodes.Tree01.geometry} material={materials.Bark} />
        <mesh geometry={nodes.Tree01_1.geometry} material={materials.Tree_Dark_Green} />
        <mesh geometry={nodes.Tree01_2.geometry} material={materials.Tree_Green} />
        <mesh geometry={nodes.Tree01_3.geometry} material={materials.Tree_Dark_Yellow} />
      </group>
      <mesh geometry={nodes.DBS_Internationl_School.geometry} material={nodes.DBS_Internationl_School.material} position={[9.668, 4.225, -25.983]} />
      <mesh geometry={nodes.Wilson_College.geometry} material={nodes.Wilson_College.material} position={[9.668, 4.225, -25.983]} />
      <mesh geometry={nodes.Malabar_Hill_Club.geometry} material={nodes.Malabar_Hill_Club.material} position={[9.668, 4.225, -25.983]} />
      <mesh geometry={nodes.Cricket_Club_Of_India.geometry} material={nodes.Cricket_Club_Of_India.material} position={[9.668, 4.225, -25.983]} />
      <mesh geometry={nodes.NCPA.geometry} material={nodes.NCPA.material} position={[9.668, 4.225, -25.983]} />
      <mesh geometry={nodes.National_Gallery_of_Modern_Art.geometry} material={nodes.National_Gallery_of_Modern_Art.material} position={[9.668, 4.225, -25.983]} />
      <mesh geometry={nodes.Shri_Walkeshware_Temple.geometry} material={nodes.Shri_Walkeshware_Temple.material} position={[9.668, 4.225, -25.983]} />
      <mesh geometry={nodes.Iskon_Temple.geometry} material={nodes.Iskon_Temple.material} position={[9.668, 4.225, -25.983]} />
      <mesh geometry={nodes.InterContinental_Dome.geometry} material={nodes.InterContinental_Dome.material} position={[9.668, 4.225, -25.983]} />
      <mesh geometry={nodes.Wasabi_by_Morimoto.geometry} material={nodes.Wasabi_by_Morimoto.material} position={[9.668, 4.225, -25.983]} />
      <mesh geometry={nodes.Trident.geometry} material={nodes.Trident.material} position={[9.668, 4.225, -25.983]} />
      <mesh geometry={nodes.The_Taj_Mahal_Palace.geometry} material={nodes.The_Taj_Mahal_Palace.material} position={[9.668, 4.225, -25.983]} />
      <mesh geometry={nodes.Wankhede_Stadium.geometry} material={nodes.Wankhede_Stadium.material} position={[9.668, 4.225, -25.983]} />
      <mesh geometry={nodes.Mahalaxmi_Race_Course.geometry} material={nodes.Mahalaxmi_Race_Course.material} position={[9.668, 4.225, -25.983]} />
      <mesh geometry={nodes.Sea.geometry} material={materials.Ocean} position={[425.914, -137.399, 812.868]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Base.geometry} material={materials.Base} position={[425.914, -137.399, 812.868]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Runwal_Malabar.geometry} material={materials.Runwal_Malabar} position={[1.194, 0, 4.653]} rotation={[-Math.PI / 2, 0, -0.42]} />
      <mesh geometry={nodes.Buildings.geometry} material={materials.Buildings} position={[2938.695, 0, -1246.65]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload(MODEL_URL)
